#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Smartdocs.Droid.Resource", IsApplication=true)]

namespace Smartdocs.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Smartdocs.Droid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Smartdocs.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Smartdocs.Droid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int act_files = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int act_lines = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int act_logs = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int act_main = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int files = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int inbox = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int invoice = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int jpg64 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int link = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int logs = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int main = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int maintenance = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int material64 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int outbox = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int payment = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int pdf64 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int photo_library64 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int pos = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int price = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int prs = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int purchase_order = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int purchase_request = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int request = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int requests = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int search = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int setting = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int splash = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int time24 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int toggle_menu = 2130837533;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int contentFrame = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int zxingscanneractivitylayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int zxingscannerfragmentlayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
